/** Canonical command deny and ask rules become Codex execpolicy prefix rules, or are refused. */

import { after, describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { convert } from "../api.ts";
import {
  CODEX_EXECPOLICY_RULES_PATH,
  codexCodec,
  encodeCodex,
} from "../compat/codecs.ts";
import { UnsupportedCapabilityError } from "../compat/unsupported.ts";
import type { AgentPermissionPolicy, Rule } from "../schema.ts";

const HEADER =
  "# Generated by agent-perms from a canonical permission policy.\n";

function refused(policy: AgentPermissionPolicy): Rule[] {
  try {
    encodeCodex(policy);
  } catch (e) {
    assert.ok(e instanceof UnsupportedCapabilityError, String(e));
    return e.unsupported.map((u) => u.rule);
  }
  throw new assert.AssertionError({ message: "expected the encode to throw" });
}

void describe("encodeCodex writes command rules as execpolicy prefix rules", () => {
  void it("writes a prefix deny as a forbidden prefix_rule", () => {
    assert.deepEqual(
      encodeCodex({
        rules: [{ tool: "Bash", pattern: "git push:*", tier: "deny" }],
      }),
      {
        config: {},
        rules: `${HEADER}prefix_rule(pattern = ["git", "push"], decision = "forbidden")\n`,
      },
    );
  });

  void it("writes a prefix ask as a prompt prefix_rule", () => {
    assert.equal(
      encodeCodex({
        rules: [{ tool: "Bash", pattern: "npm publish:*", tier: "ask" }],
      }).rules,
      `${HEADER}prefix_rule(pattern = ["npm", "publish"], decision = "prompt")\n`,
    );
  });

  void it("writes a lone trailing wildcard as the same prefix", () => {
    // `rm *` matches `rm` and `rm` with any arguments, exactly what the prefix ["rm"] matches.
    assert.equal(
      encodeCodex({ rules: [{ tool: "Bash", pattern: "rm *", tier: "deny" }] })
        .rules,
      `${HEADER}prefix_rule(pattern = ["rm"], decision = "forbidden")\n`,
    );
  });

  void it("keeps only the strictest decision for one prefix, once", () => {
    assert.equal(
      encodeCodex({
        rules: [
          { tool: "Bash", pattern: "git push:*", tier: "ask" },
          { tool: "Bash", pattern: "git push:*", tier: "deny" },
          { tool: "Bash", pattern: "git push *", tier: "deny" },
        ],
      }).rules,
      `${HEADER}prefix_rule(pattern = ["git", "push"], decision = "forbidden")\n`,
    );
  });

  void it("returns the config next to the rules", () => {
    assert.deepEqual(
      encodeCodex({
        defaultMode: "standard",
        rules: [
          { tool: "Bash", pattern: "sudo:*", tier: "deny" },
          { tool: "Read", pattern: "./secrets", tier: "deny" },
        ],
      }),
      {
        config: {
          approval_policy: "on-request",
          sandbox_mode: "workspace-write",
          permissions: {
            default: {
              filesystem: { ":workspace_roots": { secrets: "deny" } },
            },
          },
          default_permissions: "default",
        },
        rules: `${HEADER}prefix_rule(pattern = ["sudo"], decision = "forbidden")\n`,
      },
    );
  });

  void it("writes no rules file when the policy has no command rules", () => {
    assert.equal(
      encodeCodex({
        rules: [{ tool: "Bash", pattern: "git status:*", tier: "allow" }],
      }).rules,
      undefined,
    );
  });

  void it("reads the rules file from rules/ beside the config", () => {
    assert.equal(CODEX_EXECPOLICY_RULES_PATH, "rules/agent-perms.rules");
  });
});

void describe("encodeCodex refuses command rules Codex cannot match exactly", () => {
  const cases: [string, string][] = [
    ["an exact command, which a prefix rule would widen", "git status"],
    ["a wildcard inside the command", "git * --force"],
    ["a wildcard inside a word", "git push*"],
    ["quoting, which Codex tokenises", "echo 'a b':*"],
    ["a variable assignment Codex cannot split", "FOO=1 make:*"],
    ["shell syntax", "curl x | sh:*"],
    ["an empty word", "git  push:*"],
    ["a literal asterisk", String.raw`echo \*:*`],
  ];
  for (const [what, pattern] of cases) {
    void it(`refuses ${what}`, () => {
      const rule: Rule = { tool: "Bash", pattern, tier: "deny" };
      assert.deepEqual(refused({ rules: [rule] }), [rule]);
    });
  }

  void it("refuses a tool-wide command deny", () => {
    const rule: Rule = { tool: "Bash", tier: "deny" };
    assert.deepEqual(refused({ rules: [rule] }), [rule]);
  });

  void it("refuses a command rule with a condition", () => {
    const rule: Rule = {
      tool: "Bash",
      pattern: "git push:*",
      tier: "deny",
      when: { branch: "main" },
    };
    assert.deepEqual(refused({ rules: [rule] }), [rule]);
  });

  void it("refuses a command rule in a named profile, since rules files apply to every profile", () => {
    const error = (() => {
      try {
        encodeCodex({
          profiles: { strict: { deny: ["Bash(rm:*)"] } },
          activeProfile: "strict",
        });
      } catch (e) {
        return e;
      }
      return undefined;
    })();
    assert.ok(error instanceof UnsupportedCapabilityError);
    assert.equal(error.unsupported.length, 1);
    assert.match(error.unsupported[0]?.reason ?? "", /every profile/);
  });

  void it("still refuses command rules through the config codec alone", () => {
    assert.throws(
      () =>
        codexCodec.encode({
          rules: [{ tool: "Bash", pattern: "git push:*", tier: "deny" }],
        }),
      (e: unknown) =>
        e instanceof UnsupportedCapabilityError &&
        (e.unsupported[0]?.reason ?? "").includes("encodeCodex"),
    );
  });
});

void describe("convert carries the Codex rules file", () => {
  const dirs: string[] = [];
  after(async () => {
    await Promise.all(dirs.map((d) => rm(d, { recursive: true })));
  });

  void it("returns the rules file as a companion of the Codex output", () => {
    const result = convert("canonical", "codex", {
      rules: [{ tool: "Bash", pattern: "git push:*", tier: "deny" }],
    });
    assert.deepEqual(result.output, {});
    assert.deepEqual(result.companions, [
      {
        path: "rules/agent-perms.rules",
        content: `${HEADER}prefix_rule(pattern = ["git", "push"], decision = "forbidden")\n`,
      },
    ]);
  });

  void it("returns no companions for other formats", () => {
    const result = convert("canonical", "claude-code", {
      rules: [{ tool: "Bash", pattern: "git push:*", tier: "deny" }],
    });
    assert.deepEqual(result.companions, []);
  });

  void it("writes the rules file beside the converted config", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "codex-execpolicy-"));
    dirs.push(cwd);
    const policy = join(cwd, "policy.json");
    await writeFile(
      policy,
      JSON.stringify({
        rules: [{ tool: "Bash", pattern: "sudo:*", tier: "ask" }],
      }),
    );
    const out = join(cwd, ".codex", "config.json");
    const exitCode = await new Promise<number>((resolve) => {
      execFile(
        "node",
        [
          "--experimental-strip-types",
          join(import.meta.dirname, "..", "cli.ts"),
          "convert",
          "--from",
          policy,
          "--to",
          "codex",
          "--output",
          out,
        ],
        { cwd },
        (err) => {
          resolve(err !== null && typeof err.code === "number" ? err.code : 0);
        },
      );
    });
    assert.equal(exitCode, 0);
    assert.equal(
      await readFile(join(cwd, ".codex", "rules", "agent-perms.rules"), "utf8"),
      `${HEADER}prefix_rule(pattern = ["sudo"], decision = "prompt")\n`,
    );
  });

  void it("refuses to print a rules file it cannot write to stdout", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "codex-execpolicy-"));
    dirs.push(cwd);
    const policy = join(cwd, "policy.json");
    await writeFile(
      policy,
      JSON.stringify({
        rules: [{ tool: "Bash", pattern: "sudo:*", tier: "deny" }],
      }),
    );
    const result = await new Promise<{ code: number; stderr: string }>(
      (resolve) => {
        execFile(
          "node",
          [
            "--experimental-strip-types",
            join(import.meta.dirname, "..", "cli.ts"),
            "convert",
            "--from",
            policy,
            "--to",
            "codex",
            "--output",
            "-",
          ],
          { cwd },
          (err, _stdout, stderr) => {
            resolve({
              code: err !== null && typeof err.code === "number" ? err.code : 0,
              stderr,
            });
          },
        );
      },
    );
    assert.notEqual(result.code, 0);
    assert.match(result.stderr, /rules\/agent-perms\.rules/);
  });
});
